### PR TITLE
Refactoring wait helper

### PR DESCRIPTION
**Pull request by vakyla98**
Hacktoberfest PR
If you like it, please add a label ->
hacktoberfest-accepted

### CODE REVIEW

**Review by bopojoe — COMMENTED** [review]
does it produce the same effect?

**Comment by vakyla98** [comment]
Definitely yes. Also, it must work faster. Because "new Date" create a big object - "Date.now()" just get a time

**Review by bopojoe — APPROVED** [review]
Looks good so, i'll get it in, also you should have a look at [Beginbot's Stream](https://twitch.tv/beginbot) for which this bot is built, great coding stream and great community

**Comment by vakyla98** [comment]
:+1:

**Pull request merged**
